### ISSUE TITLE
Xalia v0.4.4 crashing inside GudlTokenizer

### ISSUE THREAD

**Issue by BLaDZer** [madewokherd/xalia#48]
Please help. Actually I'm getting Xalia crash in the steam, but it also reproduced in standalone version:

> Unhandled exception in Xalia:
> System.FormatException: The input string '0.2' was not in a correct format.
>    at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
>    at System.Double.Parse(String s)
>    at Xalia.Gudl.GudlTokenizer.<>c.<.cctor>b__6_7(<>f__AnonymousType7`2 <>h__TransparentIdentifier0, TextSpan dec) in D:\a\xalia\xalia\xalia\Gudl\GudlTokenizer.cs:line 60

Message looks weird to me but I cannot get what is going on. More info in the logs:
[system_info.log](https://github.com/user-attachments/files/17308620/system_info.log)
[crash.log](https://github.com/user-attachments/files/17308557/crash.log)

**Comment by madewokherd** [comment]
I forgot CultureInfo.InvariantCulture. Sorry about that. Should be an easy fix at least.

**Comment by madewokherd** [comment]
Just so I can make sure I test it, what locale are you using?

**Comment by madewokherd** [comment]
I wasn't able to reproduce this locally (I'm probably just not overriding my locale correctly) so I just went through and added InvariantCulture anywhere I could find that might be a problem.

Could you try with the current CI build? (https://github.com/madewokherd/xalia/actions/runs/11262113557/artifacts/2036979861)

**Comment by BLaDZer** [comment]
Hi, thanks for the fix!

Not sure if it's working fine but at least it stop crashing now

**Comment by madewokherd** [comment]
Thanks, closing.
