### ISSUE TITLE
Danmaku unlimited 3: Settings issue

### ISSUE THREAD

**Issue by waspennator** [madewokherd/xalia#51]
Xalia somewhat seems to work with this, but i noticed the highlighter from Xalia when moving around as well as something else that moves between each setting each time I move around. Can't really change or modify anything though as pressing a instantly starts the game, even if I'm not highlighting the start game button.

![download (2)](https://github.com/user-attachments/assets/86206c53-1315-4280-b791-5b6b3b7326e8)

**Comment by madewokherd** [comment]
Nothing we can really do when the launcher has its own gamepad support, however limited it might be.

**Comment by waspennator** [comment]
OK then
